server:
  port: 8081

spring:
  application:
    name: account
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    username: wiam
    url: jdbc:postgresql://localhost:5432/account
    password: password
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true